### ISSUE TITLE
recipient email address

### ISSUE THREAD

**Issue by eberhardst** [myspace-nu/jquery.fancyMessenger#1]
Hello Johan,
thanks for the floating-contact-button-messenger.
Where do I enter the recipient email address?
Do you have an example?
best regards

**Comment by myspace-nu** [comment]
Hi,

This plugin is just a simplified way to make a frontend for a messenger function. You still need a backend to send the message. The recepient is not limited to a person and the transport method not to just email. Potentially you could receive messages for your CRM, send push notifications or smoke signals :)

If you want to receive email from your website messenger I can recommend [Hubspot](https://www.hubspot.com/) Then you will get a CRM and messages sent to your e-mail for free.

/ Johan
